const fakeData1 = {
    jsonGeocodedData: [
        {
            name: "Allie",
            address: "4242 Branch Bend Ln, Charlotte, North Carolina, 28273",
            id: 1,
            latitude: 35.146123,
            longitude: -80.971573,
            method: null,
            type: "client",
            group: 1,
        },
        {
            name: "Anastasia",
            address: "11807 Broadwater Ln, Charlotte, North Carolina 28273",
            id: 2,
            latitude: 35.1106926,
            longitude: -80.9697304,
            method: null,
            type: "client",
            group: 1,
        },
        {
            name: "Anthony",
            address: "3707 Highview Rd, Charlotte, North Carolina, 28210",
            id: 3,
            latitude: 35.131711,
            longitude: -80.8278959,
            method: "driving",
            type: "employee",
            group: 1,
        },
        {
            name: "Danny",
            address: "226 Queens Rd #69, Charlotte, North Carolina, 28204",
            id: 4,
            latitude: 35.209572,
            longitude: -80.82841189999999,
            method: null,
            type: "client",
            group: 1,
        },
        {
            name: "Evan",
            address: "4020 Constable Ct, Charlotte, North Carolina, 28209",
            id: 5,
            latitude: 35.1809391,
            longitude: -80.8619298,
            method: "driving",
            type: "employee",
            group: 2,
        },
        {
            name: "Greg",
            address: "3122 Eastway Dr, Charlotte, NC 28205",
            id: 6,
            latitude: 35.213196,
            longitude: -80.783028,
            method: null,
            type: "client",
            group: 2,
        },
        {
            name: "James",
            address: "2135 Ferncliff Rd, Charlotte, North Carolina, 28211",
            id: 7,
            latitude: 35.16645949999999,
            longitude: -80.814832,
            method: null,
            type: "client",
            group: 2,
        },
        {
            name: "Joe",
            address: "3201 Tallia Ct, Charlotte, North Carolina, 28269",
            id: 8,
            latitude: 35.31482370000001,
            longitude: -80.79285229999999,
            method: null,
            type: "client",
            group: 2,
        },
        {
            name: "Julia",
            address: "2910 Parkway Ave, Charlotte, NC 28208",
            id: 9,
            latitude: 35.2424857,
            longitude: -80.87749319999999,
            method: null,
            type: "client",
            group: 2,
        },
        {
            name: "Lisa",
            address: "3109 Connecticut Ave, Charlotte, North Carolina, 28205",
            id: 10,
            latitude: 35.232182,
            longitude: -80.7813516,
            method: null,
            type: "client",
            group: 2,
        },
        {
            name: "Maria",
            address: "3506 Rindle Ct, Charlotte, North Carolina, 28269",
            id: 11,
            latitude: 35.3156337,
            longitude: -80.8034535,
            method: "driving",
            type: "employee",
            group: 3,
        },
        {
            name: "Nava",
            address: "3737 Winding Creek Ln, Charlotte, North Carolina, 28226",
            id: 12,
            latitude: 35.142092,
            longitude: -80.8181479,
            method: null,
            type: "client",
            group: 3,
        },
        {
            name: "Rachana",
            address: "2123 Beatties Ford Rd, Charlotte, NC 28216",
            id: 13,
            latitude: 35.2641691,
            longitude: -80.85620080000001,
            method: null,
            type: "client",
            group: 3,
        },
        {
            name: "Spencer",
            address: "3800 Shamrock Dr, Charlotte, North Carolina, 28215",
            id: 14,
            latitude: 35.2344339,
            longitude: -80.7605397,
            method: null,
            type: "client",
            group: 3,
        },
        {
            name: "Tamanna",
            address: "426 N Tryon St, Charlotte, North Carolina, 28202",
            id: 15,
            latitude: 35.2298541,
            longitude: -80.83860059999999,
            method: null,
            type: "client",
            group: 3,
        },
    ],
    transitMap: {
        3: {
            1: {
                travelTime: 23.68,
                travelTimeTraffic: 28.95,
                travelDistance: 12.86,
            },
            2: {
                travelTime: 27.07,
                travelTimeTraffic: 34.17,
                travelDistance: 13.46,
            },
            4: {
                travelTime: 19.17,
                travelTimeTraffic: 23.85,
                travelDistance: 6.65,
            },
            6: {
                travelTime: 20.33,
                travelTimeTraffic: 27.27,
                travelDistance: 7.46,
            },
            7: {
                travelTime: 10.37,
                travelTimeTraffic: 12.53,
                travelDistance: 3.46,
            },
            8: {
                travelTime: 33.3,
                travelTimeTraffic: 42.47,
                travelDistance: 19.03,
            },
            9: {
                travelTime: 25.57,
                travelTimeTraffic: 33.78,
                travelDistance: 11.75,
            },
            10: {
                travelTime: 26.38,
                travelTimeTraffic: 34.2,
                travelDistance: 9.59,
            },
            12: {
                travelTime: 5.2,
                travelTimeTraffic: 5.88,
                travelDistance: 1.36,
            },
            13: {
                travelTime: 27.32,
                travelTimeTraffic: 35.45,
                travelDistance: 13.82,
            },
            14: {
                travelTime: 25.65,
                travelTimeTraffic: 34.35,
                travelDistance: 10.02,
            },
            15: {
                travelTime: 23.9,
                travelTimeTraffic: 31.4,
                travelDistance: 12.67,
            },
        },
        5: {
            1: {
                travelTime: 19.9,
                travelTimeTraffic: 23.38,
                travelDistance: 11.31,
            },
            2: {
                travelTime: 22.05,
                travelTimeTraffic: 24.78,
                travelDistance: 12.36,
            },
            4: {
                travelTime: 15.17,
                travelTimeTraffic: 18.88,
                travelDistance: 6.98,
            },
            6: {
                travelTime: 19.33,
                travelTimeTraffic: 23.22,
                travelDistance: 10.59,
            },
            7: {
                travelTime: 11.33,
                travelTimeTraffic: 14.3,
                travelDistance: 3.62,
            },
            8: {
                travelTime: 23.17,
                travelTimeTraffic: 27.73,
                travelDistance: 13.37,
            },
            9: {
                travelTime: 15.43,
                travelTimeTraffic: 19.03,
                travelDistance: 6.1,
            },
            10: {
                travelTime: 23.05,
                travelTimeTraffic: 28.13,
                travelDistance: 10.75,
            },
            12: {
                travelTime: 14.53,
                travelTimeTraffic: 19.77,
                travelDistance: 4.63,
            },
            13: {
                travelTime: 17.2,
                travelTimeTraffic: 20.72,
                travelDistance: 8.17,
            },
            14: {
                travelTime: 24.65,
                travelTimeTraffic: 30.3,
                travelDistance: 13.16,
            },
            15: {
                travelTime: 13.78,
                travelTimeTraffic: 16.65,
                travelDistance: 7.02,
            },
        },
        11: {
            1: {
                travelTime: 28.37,
                travelTimeTraffic: 31.87,
                travelDistance: 21.7,
            },
            2: {
                travelTime: 33.42,
                travelTimeTraffic: 38.07,
                travelDistance: 23.2,
            },
            4: {
                travelTime: 21.63,
                travelTimeTraffic: 24.97,
                travelDistance: 13.1,
            },
            6: {
                travelTime: 23.83,
                travelTimeTraffic: 29.52,
                travelDistance: 8.63,
            },
            7: {
                travelTime: 29.15,
                travelTimeTraffic: 34.22,
                travelDistance: 16.62,
            },
            8: {
                travelTime: 3.28,
                travelTimeTraffic: 3.38,
                travelDistance: 0.77,
            },
            9: {
                travelTime: 18.3,
                travelTimeTraffic: 20.9,
                travelDistance: 10,
            },
            10: {
                travelTime: 20.7,
                travelTimeTraffic: 25.12,
                travelDistance: 7.44,
            },
            12: {
                travelTime: 32.62,
                travelTimeTraffic: 40.85,
                travelDistance: 19.29,
            },
            13: {
                travelTime: 15.8,
                travelTimeTraffic: 18.12,
                travelDistance: 7.29,
            },
            14: {
                travelTime: 20.62,
                travelTimeTraffic: 25.03,
                travelDistance: 7.63,
            },
            15: {
                travelTime: 17,
                travelTimeTraffic: 19.35,
                travelDistance: 9.61,
            },
        },
    },
};

const fakeData2 = {
    jsonGeocodedData: [
        {
            id: 1,
            name: "Allie",
            address: "4242 Branch Bend Ln, Charlotte, North Carolina, 28273",
            type: "client",
            method: "null",
            latitude: 35.146123,
            longitude: -80.971573,
            group: 1,
        },
        {
            id: 2,
            name: "Anastasia",
            address: "11807 Broadwater Ln, Charlotte, North Carolina 28273",
            type: "client",
            method: "null",
            latitude: 35.1106926,
            longitude: -80.9697304,
            group: 1,
        },
        {
            id: 3,
            name: "Anthony",
            address: "3707 Highview Rd, Charlotte, North Carolina, 28210",
            type: "employee",
            method: "driving",
            latitude: 35.131711,
            longitude: -80.8278959,
            group: 1,
        },
        {
            id: 4,
            name: "Danny",
            address: "226 Queens Rd #69, Charlotte, North Carolina, 28204",
            type: "client",
            method: "null",
            latitude: 35.209572,
            longitude: -80.82841189999999,
            group: 1,
        },
        {
            id: 5,
            name: "Evan",
            address: "4020 Constable Ct, Charlotte, North Carolina, 28209",
            type: "employee",
            method: "driving",
            latitude: 35.1809391,
            longitude: -80.8619298,
            group: 2,
        },
        {
            id: 6,
            name: "Greg",
            address: "3122 Eastway Dr, Charlotte, NC 28205",
            type: "client",
            method: "null",
            latitude: 35.213196,
            longitude: -80.783028,
            group: 2,
        },
        {
            id: 7,
            name: "James",
            address: "2135 Ferncliff Rd, Charlotte, North Carolina, 28211",
            type: "client",
            method: "null",
            latitude: 35.16645949999999,
            longitude: -80.814832,
            group: 2,
        },
        {
            id: 8,
            name: "Joe",
            address: "3201 Tallia Ct, Charlotte, North Carolina, 28269",
            type: "client",
            method: "null",
            latitude: 35.31482370000001,
            longitude: -80.79285229999999,
            group: 2,
        },
        {
            id: 9,
            name: "Julia",
            address: "2910 Parkway Ave, Charlotte, NC 28208",
            type: "client",
            method: "null",
            latitude: 35.2424857,
            longitude: -80.87749319999999,
            group: 2,
        },
        {
            id: 10,
            name: "Lisa",
            address: "3109 Connecticut Ave, Charlotte, North Carolina, 28205",
            type: "client",
            method: "null",
            latitude: 35.232182,
            longitude: -80.7813516,
            group: 2,
        },
        {
            id: 11,
            name: "Maria",
            address: "3506 Rindle Ct, Charlotte, North Carolina, 28269",
            type: "employee",
            method: "driving",
            latitude: 35.3156337,
            longitude: -80.8034535,
            group: 3,
        },
        {
            id: 12,
            name: "Nava",
            address: "3737 Winding Creek Ln, Charlotte, North Carolina, 28226",
            type: "client",
            method: "null",
            latitude: 35.142092,
            longitude: -80.8181479,
            group: 3,
        },
        {
            id: 13,
            name: "Rachana",
            address: "2123 Beatties Ford Rd, Charlotte, NC 28216",
            type: "client",
            method: "null",
            latitude: 35.2641691,
            longitude: -80.85620080000001,
            group: 3,
        },
        {
            id: 14,
            name: "Spencer",
            address: "3800 Shamrock Dr, Charlotte, North Carolina, 28215",
            type: "client",
            method: "null",
            latitude: 35.2344339,
            longitude: -80.7605397,
            group: 3,
        },
        {
            id: 15,
            name: "Tamanna",
            address: "426 N Tryon St, Charlotte, North Carolina, 28202",
            type: "client",
            method: "null",
            latitude: 35.2298541,
            longitude: -80.83860059999999,
            group: 3,
        },
        {
            id: 16,
            name: "Tom",
            address: "4710 Chesapeake Dr, Charlotte, NC 28216",
            type: "client",
            method: "null",
            latitude: 35.2833835,
            longitude: -80.8786063,
            group: 3,
        },
        {
            id: 17,
            name: "Aaron",
            address: "7105 University City Blvd, Charlotte, NC 28262",
            type: "client",
            method: "null",
            latitude: 35.2903841,
            longitude: -80.763172,
            group: 3,
        },
        {
            id: 18,
            name: "Bill",
            address: "2900 Rocky River Rd, Charlotte, NC 28213",
            type: "client",
            method: "null",
            latitude: 35.2751955,
            longitude: -80.7160998,
            group: 3,
        },
        {
            id: 19,
            name: "Fantasia",
            address: "5200 Brookshire Blvd, Charlotte, NC 28216",
            type: "employee",
            method: "driving",
            latitude: 35.2789653,
            longitude: -80.89119509999999,
            group: 4,
        },
        {
            id: 20,
            name: "Megan",
            address: "5923 Farm Pond Ln, Charlotte, NC 28212",
            type: "client",
            method: "null",
            latitude: 35.1988106,
            longitude: -80.7370323,
            group: 4,
        },
        {
            id: 21,
            name: "Jebediah",
            address: "10512 Idlewild Rd, Matthews, NC 28105",
            type: "client",
            method: "null",
            latitude: 35.1633207,
            longitude: -80.70214419999999,
            group: 4,
        },
        {
            id: 22,
            name: "Rudy",
            address: "4150 Yancey Rd, Charlotte, NC 28217",
            type: "client",
            method: "null",
            latitude: 35.1872759,
            longitude: -80.8817942,
            group: 4,
        },
        {
            id: 23,
            name: "Chuck",
            address: "2725 West Blvd, Charlotte, NC 28208",
            type: "client",
            method: "null",
            latitude: 35.2095867,
            longitude: -80.90941029999999,
            group: 4,
        },
        {
            id: 24,
            name: "Boris",
            address: "2701 Freedom Dr, Charlotte, NC 28208",
            type: "client",
            method: "null",
            latitude: 35.2366085,
            longitude: -80.8855979,
            group: 4,
        },
        {
            id: 25,
            name: "Ryan",
            address: "7632 Hood Rd, Charlotte, NC 28215",
            type: "employee",
            method: "driving",
            latitude: 35.24599,
            longitude: -80.690332,
            group: 5,
        },
        {
            id: 26,
            name: "Malik",
            address: "8905 Albemarle Rd, Charlotte, NC 28227",
            type: "client",
            method: "null",
            latitude: 35.2118021,
            longitude: -80.6951474,
            group: 5,
        },
        {
            id: 27,
            name: "Paul",
            address: "8711 Monroe Rd, Charlotte, NC 28212",
            type: "client",
            method: "null",
            latitude: 35.1508801,
            longitude: -80.7449091,
            group: 5,
        },
        {
            id: 28,
            name: "Jenn",
            address: "5501 Josh Birmingham Pkwy, Charlotte, NC 28208",
            type: "client",
            method: "null",
            latitude: 35.2307837,
            longitude: -80.93608359999999,
            group: 5,
        },
        {
            id: 29,
            name: "Eliza",
            address: "4300 N Tryon St, Charlotte, NC 28213",
            type: "client",
            method: "null",
            latitude: 35.2577296,
            longitude: -80.7936035,
            group: 5,
        },
        {
            id: 30,
            name: "Rina",
            address: "6514 N Tryon St, Charlotte, NC 28213",
            type: "client",
            method: "null",
            latitude: 35.2775488,
            longitude: -80.765361,
            group: 5,
        },
    ],
    transitMap: {
        3: {
            1: {
                travelTime: 23.68,
                travelTimeTraffic: 29.23,
                travelDistance: 12.86,
            },
            2: {
                travelTime: 27.07,
                travelTimeTraffic: 34.18,
                travelDistance: 13.46,
            },
            4: {
                travelTime: 19.17,
                travelTimeTraffic: 24.15,
                travelDistance: 6.65,
            },
            6: {
                travelTime: 20.33,
                travelTimeTraffic: 27.6,
                travelDistance: 7.46,
            },
            7: {
                travelTime: 10.37,
                travelTimeTraffic: 12.67,
                travelDistance: 3.46,
            },
            8: {
                travelTime: 33.3,
                travelTimeTraffic: 43.62,
                travelDistance: 19.03,
            },
            9: {
                travelTime: 25.57,
                travelTimeTraffic: 34.45,
                travelDistance: 11.75,
            },
            10: {
                travelTime: 26.38,
                travelTimeTraffic: 34.9,
                travelDistance: 9.59,
            },
            12: {
                travelTime: 5.2,
                travelTimeTraffic: 5.85,
                travelDistance: 1.36,
            },
            13: {
                travelTime: 27.32,
                travelTimeTraffic: 36.27,
                travelDistance: 13.82,
            },
            14: {
                travelTime: 25.65,
                travelTimeTraffic: 35.23,
                travelDistance: 10.02,
            },
            15: {
                travelTime: 23.9,
                travelTimeTraffic: 32.05,
                travelDistance: 12.67,
            },
            16: {
                travelTime: 28.88,
                travelTimeTraffic: 38.02,
                travelDistance: 15.56,
            },
            17: {
                travelTime: 28.53,
                travelTimeTraffic: 37.98,
                travelDistance: 18.48,
            },
            18: {
                travelTime: 34.73,
                travelTimeTraffic: 47.67,
                travelDistance: 14.35,
            },
            20: {
                travelTime: 23.93,
                travelTimeTraffic: 30.5,
                travelDistance: 8.9,
            },
            21: {
                travelTime: 26.8,
                travelTimeTraffic: 33.3,
                travelDistance: 10.69,
            },
            22: {
                travelTime: 19.73,
                travelTimeTraffic: 27.42,
                travelDistance: 7.39,
            },
            23: {
                travelTime: 22.92,
                travelTimeTraffic: 31.63,
                travelDistance: 10.34,
            },
            24: {
                travelTime: 27.27,
                travelTimeTraffic: 36.02,
                travelDistance: 12.01,
            },
            26: {
                travelTime: 29.68,
                travelTimeTraffic: 37.73,
                travelDistance: 11.66,
            },
            27: {
                travelTime: 22.47,
                travelTimeTraffic: 27.23,
                travelDistance: 8.8,
            },
            28: {
                travelTime: 23.92,
                travelTimeTraffic: 32.87,
                travelDistance: 11.74,
            },
            29: {
                travelTime: 29.67,
                travelTimeTraffic: 40.33,
                travelDistance: 11.09,
            },
            30: {
                travelTime: 30.93,
                travelTimeTraffic: 40.82,
                travelDistance: 18.94,
            },
        },
        5: {
            1: {
                travelTime: 19.9,
                travelTimeTraffic: 24.42,
                travelDistance: 11.31,
            },
            2: {
                travelTime: 22.05,
                travelTimeTraffic: 25.57,
                travelDistance: 12.36,
            },
            4: {
                travelTime: 15.17,
                travelTimeTraffic: 18.82,
                travelDistance: 6.98,
            },
            6: {
                travelTime: 19.33,
                travelTimeTraffic: 23.73,
                travelDistance: 10.59,
            },
            7: {
                travelTime: 11.33,
                travelTimeTraffic: 14.33,
                travelDistance: 3.62,
            },
            8: {
                travelTime: 23.17,
                travelTimeTraffic: 28.23,
                travelDistance: 13.37,
            },
            9: {
                travelTime: 15.43,
                travelTimeTraffic: 19.08,
                travelDistance: 6.1,
            },
            10: {
                travelTime: 23.05,
                travelTimeTraffic: 28.52,
                travelDistance: 10.75,
            },
            12: {
                travelTime: 14.53,
                travelTimeTraffic: 19.38,
                travelDistance: 4.63,
            },
            13: {
                travelTime: 17.2,
                travelTimeTraffic: 20.88,
                travelDistance: 8.17,
            },
            14: {
                travelTime: 24.65,
                travelTimeTraffic: 31.37,
                travelDistance: 13.16,
            },
            15: {
                travelTime: 13.78,
                travelTimeTraffic: 16.68,
                travelDistance: 7.02,
            },
            16: {
                travelTime: 18.77,
                travelTimeTraffic: 22.65,
                travelDistance: 9.9,
            },
            17: {
                travelTime: 18.4,
                travelTimeTraffic: 22.62,
                travelDistance: 12.83,
            },
            18: {
                travelTime: 27.6,
                travelTimeTraffic: 35.28,
                travelDistance: 16.76,
            },
            20: {
                travelTime: 23.23,
                travelTimeTraffic: 29.5,
                travelDistance: 12.63,
            },
            21: {
                travelTime: 29.92,
                travelTimeTraffic: 35.55,
                travelDistance: 16.16,
            },
            22: {
                travelTime: 5.5,
                travelTimeTraffic: 6.2,
                travelDistance: 1.5,
            },
            23: {
                travelTime: 12.3,
                travelTimeTraffic: 14.72,
                travelDistance: 5.76,
            },
            24: {
                travelTime: 17.13,
                travelTimeTraffic: 20.65,
                travelDistance: 6.35,
            },
            26: {
                travelTime: 28.45,
                travelTimeTraffic: 37.22,
                travelDistance: 15.32,
            },
            27: {
                travelTime: 26.97,
                travelTimeTraffic: 31.87,
                travelDistance: 14.3,
            },
            28: {
                travelTime: 13.32,
                travelTimeTraffic: 15.95,
                travelDistance: 7.16,
            },
            29: {
                travelTime: 20.92,
                travelTimeTraffic: 25.35,
                travelDistance: 9.81,
            },
            30: {
                travelTime: 20.82,
                travelTimeTraffic: 25.43,
                travelDistance: 13.28,
            },
        },
        11: {
            1: {
                travelTime: 28.37,
                travelTimeTraffic: 32.6,
                travelDistance: 21.7,
            },
            2: {
                travelTime: 33.42,
                travelTimeTraffic: 40.02,
                travelDistance: 23.2,
            },
            4: {
                travelTime: 21.63,
                travelTimeTraffic: 25.4,
                travelDistance: 13.1,
            },
            6: {
                travelTime: 23.83,
                travelTimeTraffic: 29.75,
                travelDistance: 8.63,
            },
            7: {
                travelTime: 29.15,
                travelTimeTraffic: 34.78,
                travelDistance: 16.62,
            },
            8: {
                travelTime: 3.28,
                travelTimeTraffic: 3.53,
                travelDistance: 0.77,
            },
            9: {
                travelTime: 18.3,
                travelTimeTraffic: 21.2,
                travelDistance: 10,
            },
            10: {
                travelTime: 20.7,
                travelTimeTraffic: 25.28,
                travelDistance: 7.44,
            },
            12: {
                travelTime: 32.62,
                travelTimeTraffic: 42.12,
                travelDistance: 19.29,
            },
            13: {
                travelTime: 15.8,
                travelTimeTraffic: 18.35,
                travelDistance: 7.29,
            },
            14: {
                travelTime: 20.62,
                travelTimeTraffic: 25.18,
                travelDistance: 7.63,
            },
            15: {
                travelTime: 17,
                travelTimeTraffic: 19.63,
                travelDistance: 9.61,
            },
            16: {
                travelTime: 17.6,
                travelTimeTraffic: 20.35,
                travelDistance: 8.6,
            },
            17: {
                travelTime: 9.4,
                travelTimeTraffic: 10.92,
                travelDistance: 3.91,
            },
            18: {
                travelTime: 17.45,
                travelTimeTraffic: 21.25,
                travelDistance: 7.23,
            },
            20: {
                travelTime: 27.13,
                travelTimeTraffic: 32.6,
                travelDistance: 16.31,
            },
            21: {
                travelTime: 33.8,
                travelTimeTraffic: 38.65,
                travelDistance: 19.85,
            },
            22: {
                travelTime: 22.4,
                travelTimeTraffic: 26.9,
                travelDistance: 13.33,
            },
            23: {
                travelTime: 21.93,
                travelTimeTraffic: 26.02,
                travelDistance: 12.74,
            },
            24: {
                travelTime: 19.82,
                travelTimeTraffic: 23.22,
                travelDistance: 10.53,
            },
            26: {
                travelTime: 26.47,
                travelTimeTraffic: 31.5,
                travelDistance: 19.39,
            },
            27: {
                travelTime: 30.87,
                travelTimeTraffic: 34.97,
                travelDistance: 17.98,
            },
            28: {
                travelTime: 19.02,
                travelTimeTraffic: 21.77,
                travelDistance: 13.03,
            },
            29: {
                travelTime: 13.95,
                travelTimeTraffic: 16.92,
                travelDistance: 4.9,
            },
            30: {
                travelTime: 14.38,
                travelTimeTraffic: 16.72,
                travelDistance: 5.07,
            },
        },
        19: {
            1: {
                travelTime: 21.83,
                travelTimeTraffic: 26.07,
                travelDistance: 15.49,
            },
            2: {
                travelTime: 28.9,
                travelTimeTraffic: 35.13,
                travelDistance: 20.38,
            },
            4: {
                travelTime: 17.25,
                travelTimeTraffic: 21.02,
                travelDistance: 8.76,
            },
            6: {
                travelTime: 18.55,
                travelTimeTraffic: 22.08,
                travelDistance: 9.98,
            },
            7: {
                travelTime: 24.45,
                travelTimeTraffic: 30.03,
                travelDistance: 12.32,
            },
            8: {
                travelTime: 19.53,
                travelTimeTraffic: 23.72,
                travelDistance: 9.43,
            },
            9: {
                travelTime: 10.8,
                travelTimeTraffic: 13.15,
                travelDistance: 3.46,
            },
            10: {
                travelTime: 21.75,
                travelTimeTraffic: 25.8,
                travelDistance: 8.99,
            },
            12: {
                travelTime: 28.23,
                travelTimeTraffic: 37.73,
                travelDistance: 14.94,
            },
            13: {
                travelTime: 12.12,
                travelTimeTraffic: 14.83,
                travelDistance: 3.96,
            },
            14: {
                travelTime: 23.47,
                travelTimeTraffic: 29.5,
                travelDistance: 11.09,
            },
            15: {
                travelTime: 12.32,
                travelTimeTraffic: 14.87,
                travelDistance: 5.31,
            },
            16: {
                travelTime: 6.87,
                travelTimeTraffic: 7.05,
                travelDistance: 1.98,
            },
            17: {
                travelTime: 14.77,
                travelTimeTraffic: 18.08,
                travelDistance: 8.89,
            },
            18: {
                travelTime: 23.97,
                travelTimeTraffic: 30.75,
                travelDistance: 12.82,
            },
            20: {
                travelTime: 22.45,
                travelTimeTraffic: 27.83,
                travelDistance: 12.01,
            },
            21: {
                travelTime: 29.12,
                travelTimeTraffic: 33.88,
                travelDistance: 15.54,
            },
            22: {
                travelTime: 18.03,
                travelTimeTraffic: 22.52,
                travelDistance: 8.98,
            },
            23: {
                travelTime: 15.43,
                travelTimeTraffic: 19.13,
                travelDistance: 8,
            },
            24: {
                travelTime: 13.27,
                travelTimeTraffic: 16.68,
                travelDistance: 4.31,
            },
            26: {
                travelTime: 27.65,
                travelTimeTraffic: 35.55,
                travelDistance: 14.7,
            },
            27: {
                travelTime: 26.18,
                travelTimeTraffic: 30.22,
                travelDistance: 13.68,
            },
            28: {
                travelTime: 12.47,
                travelTimeTraffic: 15.23,
                travelDistance: 6.82,
            },
            29: {
                travelTime: 16.8,
                travelTimeTraffic: 21.23,
                travelDistance: 8.35,
            },
            30: {
                travelTime: 17.17,
                travelTimeTraffic: 20.92,
                travelDistance: 9.34,
            },
        },
        25: {
            1: {
                travelTime: 38.07,
                travelTimeTraffic: 43.78,
                travelDistance: 28.4,
            },
            2: {
                travelTime: 41.18,
                travelTimeTraffic: 51.73,
                travelDistance: 26.9,
            },
            4: {
                travelTime: 23.87,
                travelTimeTraffic: 31.28,
                travelDistance: 11.56,
            },
            6: {
                travelTime: 19.53,
                travelTimeTraffic: 25.52,
                travelDistance: 8.71,
            },
            7: {
                travelTime: 26.93,
                travelTimeTraffic: 34.12,
                travelDistance: 10.81,
            },
            8: {
                travelTime: 21.8,
                travelTimeTraffic: 26.23,
                travelDistance: 10.05,
            },
            9: {
                travelTime: 27.82,
                travelTimeTraffic: 34.58,
                travelDistance: 14.91,
            },
            10: {
                travelTime: 17.98,
                travelTimeTraffic: 20.35,
                travelDistance: 7.01,
            },
            12: {
                travelTime: 29.23,
                travelTimeTraffic: 35.4,
                travelDistance: 12.52,
            },
            13: {
                travelTime: 25.5,
                travelTimeTraffic: 29.53,
                travelDistance: 13.99,
            },
            14: {
                travelTime: 13.07,
                travelTimeTraffic: 14.97,
                travelDistance: 5.36,
            },
            15: {
                travelTime: 23.55,
                travelTimeTraffic: 30.22,
                travelDistance: 12.17,
            },
            16: {
                travelTime: 27.3,
                travelTimeTraffic: 31.52,
                travelDistance: 15.29,
            },
            17: {
                travelTime: 16.5,
                travelTimeTraffic: 19.85,
                travelDistance: 7.62,
            },
            18: {
                travelTime: 7.67,
                travelTimeTraffic: 8.87,
                travelDistance: 3.55,
            },
            20: {
                travelTime: 14.82,
                travelTimeTraffic: 19.05,
                travelDistance: 5.61,
            },
            21: {
                travelTime: 20.17,
                travelTimeTraffic: 23.58,
                travelDistance: 8.22,
            },
            22: {
                travelTime: 30.17,
                travelTimeTraffic: 38.62,
                travelDistance: 17.03,
            },
            23: {
                travelTime: 29.42,
                travelTimeTraffic: 37.12,
                travelDistance: 16.44,
            },
            24: {
                travelTime: 29.5,
                travelTimeTraffic: 36.13,
                travelDistance: 15.16,
            },
            26: {
                travelTime: 10.37,
                travelTimeTraffic: 12.25,
                travelDistance: 4.23,
            },
            27: {
                travelTime: 23.15,
                travelTimeTraffic: 28.05,
                travelDistance: 8.87,
            },
            28: {
                travelTime: 28.72,
                travelTimeTraffic: 32.95,
                travelDistance: 19.73,
            },
            29: {
                travelTime: 19.97,
                travelTimeTraffic: 22.5,
                travelDistance: 7.77,
            },
            30: {
                travelTime: 17.67,
                travelTimeTraffic: 20.53,
                travelDistance: 7.87,
            },
        },
    },
};

const fakeData1Unassigned = {
    jsonGeocodedData: [
        {
            name: "Allie",
            address: "4242 Branch Bend Ln, Charlotte, North Carolina, 28273",
            id: 1,
            latitude: 35.146123,
            longitude: -80.971573,
            method: null,
            type: "client",
            group: 1,
        },
        {
            name: "Anastasia",
            address: "11807 Broadwater Ln, Charlotte, North Carolina 28273",
            id: 2,
            latitude: 35.1106926,
            longitude: -80.9697304,
            method: null,
            type: "client",
            group: 1,
        },
        {
            name: "Anthony",
            address: "3707 Highview Rd, Charlotte, North Carolina, 28210",
            id: 3,
            latitude: 35.131711,
            longitude: -80.8278959,
            method: "driving",
            type: "employee",
            group: 1,
        },
        {
            name: "Danny",
            address: "226 Queens Rd #69, Charlotte, North Carolina, 28204",
            id: 4,
            latitude: 35.209572,
            longitude: -80.82841189999999,
            method: null,
            type: "client",
            group: 1,
        },
        {
            name: "Evan",
            address: "4020 Constable Ct, Charlotte, North Carolina, 28209",
            id: 5,
            latitude: 35.1809391,
            longitude: -80.8619298,
            method: "driving",
            type: "employee",
            group: 2,
        },
        {
            name: "Greg",
            address: "3122 Eastway Dr, Charlotte, NC 28205",
            id: 6,
            latitude: 35.213196,
            longitude: -80.783028,
            method: null,
            type: "client",
            group: 2,
        },
        {
            name: "James",
            address: "2135 Ferncliff Rd, Charlotte, North Carolina, 28211",
            id: 7,
            latitude: 35.16645949999999,
            longitude: -80.814832,
            method: null,
            type: "client",
            group: 2,
        },
        {
            name: "Joe",
            address: "3201 Tallia Ct, Charlotte, North Carolina, 28269",
            id: 8,
            latitude: 35.31482370000001,
            longitude: -80.79285229999999,
            method: null,
            type: "client",
            group: 2,
        },
        {
            name: "Julia",
            address: "2910 Parkway Ave, Charlotte, NC 28208",
            id: 9,
            latitude: 35.2424857,
            longitude: -80.87749319999999,
            method: null,
            type: "client",
            group: 1,
        },
        {
            name: "Lisa",
            address: "3109 Connecticut Ave, Charlotte, North Carolina, 28205",
            id: 10,
            latitude: 35.232182,
            longitude: -80.7813516,
            method: null,
            type: "client",
            group: 3,
        },
        {
            name: "Maria",
            address: "3506 Rindle Ct, Charlotte, North Carolina, 28269",
            id: 11,
            latitude: 35.3156337,
            longitude: -80.8034535,
            method: "driving",
            type: "employee",
            group: 3,
        },
        {
            name: "Nava",
            address: "3737 Winding Creek Ln, Charlotte, North Carolina, 28226",
            id: 12,
            latitude: 35.142092,
            longitude: -80.8181479,
            method: null,
            type: "client",
            group: 3,
        },
        {
            name: "Rachana",
            address: "2123 Beatties Ford Rd, Charlotte, NC 28216",
            id: 13,
            latitude: 35.2641691,
            longitude: -80.85620080000001,
            method: null,
            type: "client",
            group: 3,
        },
        {
            name: "Spencer",
            address: "3800 Shamrock Dr, Charlotte, North Carolina, 28215",
            id: 14,
            latitude: 35.2344339,
            longitude: -80.7605397,
            method: null,
            type: "client",
            group: 3,
        },
        {
            name: "Tamanna",
            address: "426 N Tryon St, Charlotte, North Carolina, 28202",
            id: 15,
            latitude: 35.2298541,
            longitude: -80.83860059999999,
            method: null,
            type: "client",
            group: null,
        },
    ],
    transitMap: {
        3: {
            1: {
                travelTime: 23.68,
                travelTimeTraffic: 28.95,
                travelDistance: 12.86,
            },
            2: {
                travelTime: 27.07,
                travelTimeTraffic: 34.17,
                travelDistance: 13.46,
            },
            4: {
                travelTime: 19.17,
                travelTimeTraffic: 23.85,
                travelDistance: 6.65,
            },
            6: {
                travelTime: 20.33,
                travelTimeTraffic: 27.27,
                travelDistance: 7.46,
            },
            7: {
                travelTime: 10.37,
                travelTimeTraffic: 12.53,
                travelDistance: 3.46,
            },
            8: {
                travelTime: 33.3,
                travelTimeTraffic: 42.47,
                travelDistance: 19.03,
            },
            9: {
                travelTime: 25.57,
                travelTimeTraffic: 33.78,
                travelDistance: 11.75,
            },
            10: {
                travelTime: 26.38,
                travelTimeTraffic: 34.2,
                travelDistance: 9.59,
            },
            12: {
                travelTime: 5.2,
                travelTimeTraffic: 5.88,
                travelDistance: 1.36,
            },
            13: {
                travelTime: 27.32,
                travelTimeTraffic: 35.45,
                travelDistance: 13.82,
            },
            14: {
                travelTime: 25.65,
                travelTimeTraffic: 34.35,
                travelDistance: 10.02,
            },
            15: {
                travelTime: 23.9,
                travelTimeTraffic: 31.4,
                travelDistance: 12.67,
            },
        },
        5: {
            1: {
                travelTime: 19.9,
                travelTimeTraffic: 23.38,
                travelDistance: 11.31,
            },
            2: {
                travelTime: 22.05,
                travelTimeTraffic: 24.78,
                travelDistance: 12.36,
            },
            4: {
                travelTime: 15.17,
                travelTimeTraffic: 18.88,
                travelDistance: 6.98,
            },
            6: {
                travelTime: 19.33,
                travelTimeTraffic: 23.22,
                travelDistance: 10.59,
            },
            7: {
                travelTime: 11.33,
                travelTimeTraffic: 14.3,
                travelDistance: 3.62,
            },
            8: {
                travelTime: 23.17,
                travelTimeTraffic: 27.73,
                travelDistance: 13.37,
            },
            9: {
                travelTime: 15.43,
                travelTimeTraffic: 19.03,
                travelDistance: 6.1,
            },
            10: {
                travelTime: 23.05,
                travelTimeTraffic: 28.13,
                travelDistance: 10.75,
            },
            12: {
                travelTime: 14.53,
                travelTimeTraffic: 19.77,
                travelDistance: 4.63,
            },
            13: {
                travelTime: 17.2,
                travelTimeTraffic: 20.72,
                travelDistance: 8.17,
            },
            14: {
                travelTime: 24.65,
                travelTimeTraffic: 30.3,
                travelDistance: 13.16,
            },
            15: {
                travelTime: 13.78,
                travelTimeTraffic: 16.65,
                travelDistance: 7.02,
            },
        },
        11: {
            1: {
                travelTime: 28.37,
                travelTimeTraffic: 31.87,
                travelDistance: 21.7,
            },
            2: {
                travelTime: 33.42,
                travelTimeTraffic: 38.07,
                travelDistance: 23.2,
            },
            4: {
                travelTime: 21.63,
                travelTimeTraffic: 24.97,
                travelDistance: 13.1,
            },
            6: {
                travelTime: 23.83,
                travelTimeTraffic: 29.52,
                travelDistance: 8.63,
            },
            7: {
                travelTime: 29.15,
                travelTimeTraffic: 34.22,
                travelDistance: 16.62,
            },
            8: {
                travelTime: 3.28,
                travelTimeTraffic: 3.38,
                travelDistance: 0.77,
            },
            9: {
                travelTime: 18.3,
                travelTimeTraffic: 20.9,
                travelDistance: 10,
            },
            10: {
                travelTime: 20.7,
                travelTimeTraffic: 25.12,
                travelDistance: 7.44,
            },
            12: {
                travelTime: 32.62,
                travelTimeTraffic: 40.85,
                travelDistance: 19.29,
            },
            13: {
                travelTime: 15.8,
                travelTimeTraffic: 18.12,
                travelDistance: 7.29,
            },
            14: {
                travelTime: 20.62,
                travelTimeTraffic: 25.03,
                travelDistance: 7.63,
            },
            15: {
                travelTime: 17,
                travelTimeTraffic: 19.35,
                travelDistance: 9.61,
            },
        },
    },
};

const fakeData2Unassigned = {
    jsonGeocodedData: [
        {
            id: 1,
            name: "Allie",
            address: "4242 Branch Bend Ln, Charlotte, North Carolina, 28273",
            type: "client",
            method: "null",
            latitude: 35.146123,
            longitude: -80.971573,
            group: 1,
        },
        {
            id: 2,
            name: "Anastasia",
            address: "11807 Broadwater Ln, Charlotte, North Carolina 28273",
            type: "client",
            method: "null",
            latitude: 35.1106926,
            longitude: -80.9697304,
            group: 1,
        },
        {
            id: 3,
            name: "Anthony",
            address: "3707 Highview Rd, Charlotte, North Carolina, 28210",
            type: "employee",
            method: "driving",
            latitude: 35.131711,
            longitude: -80.8278959,
            group: 1,
        },
        {
            id: 4,
            name: "Danny",
            address: "226 Queens Rd #69, Charlotte, North Carolina, 28204",
            type: "client",
            method: "null",
            latitude: 35.209572,
            longitude: -80.82841189999999,
            group: null,
        },
        {
            id: 5,
            name: "Evan",
            address: "4020 Constable Ct, Charlotte, North Carolina, 28209",
            type: "employee",
            method: "driving",
            latitude: 35.1809391,
            longitude: -80.8619298,
            group: 2,
        },
        {
            id: 6,
            name: "Greg",
            address: "3122 Eastway Dr, Charlotte, NC 28205",
            type: "client",
            method: "null",
            latitude: 35.213196,
            longitude: -80.783028,
            group: 2,
        },
        {
            id: 7,
            name: "James",
            address: "2135 Ferncliff Rd, Charlotte, North Carolina, 28211",
            type: "client",
            method: "null",
            latitude: 35.16645949999999,
            longitude: -80.814832,
            group: null,
        },
        {
            id: 8,
            name: "Joe",
            address: "3201 Tallia Ct, Charlotte, North Carolina, 28269",
            type: "client",
            method: "null",
            latitude: 35.31482370000001,
            longitude: -80.79285229999999,
            group: 2,
        },
        {
            id: 9,
            name: "Julia",
            address: "2910 Parkway Ave, Charlotte, NC 28208",
            type: "client",
            method: "null",
            latitude: 35.2424857,
            longitude: -80.87749319999999,
            group: 2,
        },
        {
            id: 10,
            name: "Lisa",
            address: "3109 Connecticut Ave, Charlotte, North Carolina, 28205",
            type: "client",
            method: "null",
            latitude: 35.232182,
            longitude: -80.7813516,
            group: 2,
        },
        {
            id: 11,
            name: "Maria",
            address: "3506 Rindle Ct, Charlotte, North Carolina, 28269",
            type: "employee",
            method: "driving",
            latitude: 35.3156337,
            longitude: -80.8034535,
            group: 3,
        },
        {
            id: 12,
            name: "Nava",
            address: "3737 Winding Creek Ln, Charlotte, North Carolina, 28226",
            type: "client",
            method: "null",
            latitude: 35.142092,
            longitude: -80.8181479,
            group: 3,
        },
        {
            id: 13,
            name: "Rachana",
            address: "2123 Beatties Ford Rd, Charlotte, NC 28216",
            type: "client",
            method: "null",
            latitude: 35.2641691,
            longitude: -80.85620080000001,
            group: 3,
        },
        {
            id: 14,
            name: "Spencer",
            address: "3800 Shamrock Dr, Charlotte, North Carolina, 28215",
            type: "client",
            method: "null",
            latitude: 35.2344339,
            longitude: -80.7605397,
            group: 3,
        },
        {
            id: 15,
            name: "Tamanna",
            address: "426 N Tryon St, Charlotte, North Carolina, 28202",
            type: "client",
            method: "null",
            latitude: 35.2298541,
            longitude: -80.83860059999999,
            group: null,
        },
        {
            id: 16,
            name: "Tom",
            address: "4710 Chesapeake Dr, Charlotte, NC 28216",
            type: "client",
            method: "null",
            latitude: 35.2833835,
            longitude: -80.8786063,
            group: 3,
        },
        {
            id: 17,
            name: "Aaron",
            address: "7105 University City Blvd, Charlotte, NC 28262",
            type: "client",
            method: "null",
            latitude: 35.2903841,
            longitude: -80.763172,
            group: 3,
        },
        {
            id: 18,
            name: "Bill",
            address: "2900 Rocky River Rd, Charlotte, NC 28213",
            type: "client",
            method: "null",
            latitude: 35.2751955,
            longitude: -80.7160998,
            group: 3,
        },
        {
            id: 19,
            name: "Fantasia",
            address: "5200 Brookshire Blvd, Charlotte, NC 28216",
            type: "employee",
            method: "driving",
            latitude: 35.2789653,
            longitude: -80.89119509999999,
            group: 4,
        },
        {
            id: 20,
            name: "Megan",
            address: "5923 Farm Pond Ln, Charlotte, NC 28212",
            type: "client",
            method: "null",
            latitude: 35.1988106,
            longitude: -80.7370323,
            group: 4,
        },
        {
            id: 21,
            name: "Jebediah",
            address: "10512 Idlewild Rd, Matthews, NC 28105",
            type: "client",
            method: "null",
            latitude: 35.1633207,
            longitude: -80.70214419999999,
            group: 4,
        },
        {
            id: 22,
            name: "Rudy",
            address: "4150 Yancey Rd, Charlotte, NC 28217",
            type: "client",
            method: "null",
            latitude: 35.1872759,
            longitude: -80.8817942,
            group: 4,
        },
        {
            id: 23,
            name: "Chuck",
            address: "2725 West Blvd, Charlotte, NC 28208",
            type: "client",
            method: "null",
            latitude: 35.2095867,
            longitude: -80.90941029999999,
            group: 4,
        },
        {
            id: 24,
            name: "Boris",
            address: "2701 Freedom Dr, Charlotte, NC 28208",
            type: "client",
            method: "null",
            latitude: 35.2366085,
            longitude: -80.8855979,
            group: null,
        },
        {
            id: 25,
            name: "Ryan",
            address: "7632 Hood Rd, Charlotte, NC 28215",
            type: "employee",
            method: "driving",
            latitude: 35.24599,
            longitude: -80.690332,
            group: 5,
        },
        {
            id: 26,
            name: "Malik",
            address: "8905 Albemarle Rd, Charlotte, NC 28227",
            type: "client",
            method: "null",
            latitude: 35.2118021,
            longitude: -80.6951474,
            group: 5,
        },
        {
            id: 27,
            name: "Paul",
            address: "8711 Monroe Rd, Charlotte, NC 28212",
            type: "client",
            method: "null",
            latitude: 35.1508801,
            longitude: -80.7449091,
            group: 5,
        },
        {
            id: 28,
            name: "Jenn",
            address: "5501 Josh Birmingham Pkwy, Charlotte, NC 28208",
            type: "client",
            method: "null",
            latitude: 35.2307837,
            longitude: -80.93608359999999,
            group: null,
        },
        {
            id: 29,
            name: "Eliza",
            address: "4300 N Tryon St, Charlotte, NC 28213",
            type: "client",
            method: "null",
            latitude: 35.2577296,
            longitude: -80.7936035,
            group: 5,
        },
        {
            id: 30,
            name: "Rina",
            address: "6514 N Tryon St, Charlotte, NC 28213",
            type: "client",
            method: "null",
            latitude: 35.2775488,
            longitude: -80.765361,
            group: 5,
        },
    ],
    transitMap: {
        3: {
            1: {
                travelTime: 23.68,
                travelTimeTraffic: 29.23,
                travelDistance: 12.86,
            },
            2: {
                travelTime: 27.07,
                travelTimeTraffic: 34.18,
                travelDistance: 13.46,
            },
            4: {
                travelTime: 19.17,
                travelTimeTraffic: 24.15,
                travelDistance: 6.65,
            },
            6: {
                travelTime: 20.33,
                travelTimeTraffic: 27.6,
                travelDistance: 7.46,
            },
            7: {
                travelTime: 10.37,
                travelTimeTraffic: 12.67,
                travelDistance: 3.46,
            },
            8: {
                travelTime: 33.3,
                travelTimeTraffic: 43.62,
                travelDistance: 19.03,
            },
            9: {
                travelTime: 25.57,
                travelTimeTraffic: 34.45,
                travelDistance: 11.75,
            },
            10: {
                travelTime: 26.38,
                travelTimeTraffic: 34.9,
                travelDistance: 9.59,
            },
            12: {
                travelTime: 5.2,
                travelTimeTraffic: 5.85,
                travelDistance: 1.36,
            },
            13: {
                travelTime: 27.32,
                travelTimeTraffic: 36.27,
                travelDistance: 13.82,
            },
            14: {
                travelTime: 25.65,
                travelTimeTraffic: 35.23,
                travelDistance: 10.02,
            },
            15: {
                travelTime: 23.9,
                travelTimeTraffic: 32.05,
                travelDistance: 12.67,
            },
            16: {
                travelTime: 28.88,
                travelTimeTraffic: 38.02,
                travelDistance: 15.56,
            },
            17: {
                travelTime: 28.53,
                travelTimeTraffic: 37.98,
                travelDistance: 18.48,
            },
            18: {
                travelTime: 34.73,
                travelTimeTraffic: 47.67,
                travelDistance: 14.35,
            },
            20: {
                travelTime: 23.93,
                travelTimeTraffic: 30.5,
                travelDistance: 8.9,
            },
            21: {
                travelTime: 26.8,
                travelTimeTraffic: 33.3,
                travelDistance: 10.69,
            },
            22: {
                travelTime: 19.73,
                travelTimeTraffic: 27.42,
                travelDistance: 7.39,
            },
            23: {
                travelTime: 22.92,
                travelTimeTraffic: 31.63,
                travelDistance: 10.34,
            },
            24: {
                travelTime: 27.27,
                travelTimeTraffic: 36.02,
                travelDistance: 12.01,
            },
            26: {
                travelTime: 29.68,
                travelTimeTraffic: 37.73,
                travelDistance: 11.66,
            },
            27: {
                travelTime: 22.47,
                travelTimeTraffic: 27.23,
                travelDistance: 8.8,
            },
            28: {
                travelTime: 23.92,
                travelTimeTraffic: 32.87,
                travelDistance: 11.74,
            },
            29: {
                travelTime: 29.67,
                travelTimeTraffic: 40.33,
                travelDistance: 11.09,
            },
            30: {
                travelTime: 30.93,
                travelTimeTraffic: 40.82,
                travelDistance: 18.94,
            },
        },
        5: {
            1: {
                travelTime: 19.9,
                travelTimeTraffic: 24.42,
                travelDistance: 11.31,
            },
            2: {
                travelTime: 22.05,
                travelTimeTraffic: 25.57,
                travelDistance: 12.36,
            },
            4: {
                travelTime: 15.17,
                travelTimeTraffic: 18.82,
                travelDistance: 6.98,
            },
            6: {
                travelTime: 19.33,
                travelTimeTraffic: 23.73,
                travelDistance: 10.59,
            },
            7: {
                travelTime: 11.33,
                travelTimeTraffic: 14.33,
                travelDistance: 3.62,
            },
            8: {
                travelTime: 23.17,
                travelTimeTraffic: 28.23,
                travelDistance: 13.37,
            },
            9: {
                travelTime: 15.43,
                travelTimeTraffic: 19.08,
                travelDistance: 6.1,
            },
            10: {
                travelTime: 23.05,
                travelTimeTraffic: 28.52,
                travelDistance: 10.75,
            },
            12: {
                travelTime: 14.53,
                travelTimeTraffic: 19.38,
                travelDistance: 4.63,
            },
            13: {
                travelTime: 17.2,
                travelTimeTraffic: 20.88,
                travelDistance: 8.17,
            },
            14: {
                travelTime: 24.65,
                travelTimeTraffic: 31.37,
                travelDistance: 13.16,
            },
            15: {
                travelTime: 13.78,
                travelTimeTraffic: 16.68,
                travelDistance: 7.02,
            },
            16: {
                travelTime: 18.77,
                travelTimeTraffic: 22.65,
                travelDistance: 9.9,
            },
            17: {
                travelTime: 18.4,
                travelTimeTraffic: 22.62,
                travelDistance: 12.83,
            },
            18: {
                travelTime: 27.6,
                travelTimeTraffic: 35.28,
                travelDistance: 16.76,
            },
            20: {
                travelTime: 23.23,
                travelTimeTraffic: 29.5,
                travelDistance: 12.63,
            },
            21: {
                travelTime: 29.92,
                travelTimeTraffic: 35.55,
                travelDistance: 16.16,
            },
            22: {
                travelTime: 5.5,
                travelTimeTraffic: 6.2,
                travelDistance: 1.5,
            },
            23: {
                travelTime: 12.3,
                travelTimeTraffic: 14.72,
                travelDistance: 5.76,
            },
            24: {
                travelTime: 17.13,
                travelTimeTraffic: 20.65,
                travelDistance: 6.35,
            },
            26: {
                travelTime: 28.45,
                travelTimeTraffic: 37.22,
                travelDistance: 15.32,
            },
            27: {
                travelTime: 26.97,
                travelTimeTraffic: 31.87,
                travelDistance: 14.3,
            },
            28: {
                travelTime: 13.32,
                travelTimeTraffic: 15.95,
                travelDistance: 7.16,
            },
            29: {
                travelTime: 20.92,
                travelTimeTraffic: 25.35,
                travelDistance: 9.81,
            },
            30: {
                travelTime: 20.82,
                travelTimeTraffic: 25.43,
                travelDistance: 13.28,
            },
        },
        11: {
            1: {
                travelTime: 28.37,
                travelTimeTraffic: 32.6,
                travelDistance: 21.7,
            },
            2: {
                travelTime: 33.42,
                travelTimeTraffic: 40.02,
                travelDistance: 23.2,
            },
            4: {
                travelTime: 21.63,
                travelTimeTraffic: 25.4,
                travelDistance: 13.1,
            },
            6: {
                travelTime: 23.83,
                travelTimeTraffic: 29.75,
                travelDistance: 8.63,
            },
            7: {
                travelTime: 29.15,
                travelTimeTraffic: 34.78,
                travelDistance: 16.62,
            },
            8: {
                travelTime: 3.28,
                travelTimeTraffic: 3.53,
                travelDistance: 0.77,
            },
            9: {
                travelTime: 18.3,
                travelTimeTraffic: 21.2,
                travelDistance: 10,
            },
            10: {
                travelTime: 20.7,
                travelTimeTraffic: 25.28,
                travelDistance: 7.44,
            },
            12: {
                travelTime: 32.62,
                travelTimeTraffic: 42.12,
                travelDistance: 19.29,
            },
            13: {
                travelTime: 15.8,
                travelTimeTraffic: 18.35,
                travelDistance: 7.29,
            },
            14: {
                travelTime: 20.62,
                travelTimeTraffic: 25.18,
                travelDistance: 7.63,
            },
            15: {
                travelTime: 17,
                travelTimeTraffic: 19.63,
                travelDistance: 9.61,
            },
            16: {
                travelTime: 17.6,
                travelTimeTraffic: 20.35,
                travelDistance: 8.6,
            },
            17: {
                travelTime: 9.4,
                travelTimeTraffic: 10.92,
                travelDistance: 3.91,
            },
            18: {
                travelTime: 17.45,
                travelTimeTraffic: 21.25,
                travelDistance: 7.23,
            },
            20: {
                travelTime: 27.13,
                travelTimeTraffic: 32.6,
                travelDistance: 16.31,
            },
            21: {
                travelTime: 33.8,
                travelTimeTraffic: 38.65,
                travelDistance: 19.85,
            },
            22: {
                travelTime: 22.4,
                travelTimeTraffic: 26.9,
                travelDistance: 13.33,
            },
            23: {
                travelTime: 21.93,
                travelTimeTraffic: 26.02,
                travelDistance: 12.74,
            },
            24: {
                travelTime: 19.82,
                travelTimeTraffic: 23.22,
                travelDistance: 10.53,
            },
            26: {
                travelTime: 26.47,
                travelTimeTraffic: 31.5,
                travelDistance: 19.39,
            },
            27: {
                travelTime: 30.87,
                travelTimeTraffic: 34.97,
                travelDistance: 17.98,
            },
            28: {
                travelTime: 19.02,
                travelTimeTraffic: 21.77,
                travelDistance: 13.03,
            },
            29: {
                travelTime: 13.95,
                travelTimeTraffic: 16.92,
                travelDistance: 4.9,
            },
            30: {
                travelTime: 14.38,
                travelTimeTraffic: 16.72,
                travelDistance: 5.07,
            },
        },
        19: {
            1: {
                travelTime: 21.83,
                travelTimeTraffic: 26.07,
                travelDistance: 15.49,
            },
            2: {
                travelTime: 28.9,
                travelTimeTraffic: 35.13,
                travelDistance: 20.38,
            },
            4: {
                travelTime: 17.25,
                travelTimeTraffic: 21.02,
                travelDistance: 8.76,
            },
            6: {
                travelTime: 18.55,
                travelTimeTraffic: 22.08,
                travelDistance: 9.98,
            },
            7: {
                travelTime: 24.45,
                travelTimeTraffic: 30.03,
                travelDistance: 12.32,
            },
            8: {
                travelTime: 19.53,
                travelTimeTraffic: 23.72,
                travelDistance: 9.43,
            },
            9: {
                travelTime: 10.8,
                travelTimeTraffic: 13.15,
                travelDistance: 3.46,
            },
            10: {
                travelTime: 21.75,
                travelTimeTraffic: 25.8,
                travelDistance: 8.99,
            },
            12: {
                travelTime: 28.23,
                travelTimeTraffic: 37.73,
                travelDistance: 14.94,
            },
            13: {
                travelTime: 12.12,
                travelTimeTraffic: 14.83,
                travelDistance: 3.96,
            },
            14: {
                travelTime: 23.47,
                travelTimeTraffic: 29.5,
                travelDistance: 11.09,
            },
            15: {
                travelTime: 12.32,
                travelTimeTraffic: 14.87,
                travelDistance: 5.31,
            },
            16: {
                travelTime: 6.87,
                travelTimeTraffic: 7.05,
                travelDistance: 1.98,
            },
            17: {
                travelTime: 14.77,
                travelTimeTraffic: 18.08,
                travelDistance: 8.89,
            },
            18: {
                travelTime: 23.97,
                travelTimeTraffic: 30.75,
                travelDistance: 12.82,
            },
            20: {
                travelTime: 22.45,
                travelTimeTraffic: 27.83,
                travelDistance: 12.01,
            },
            21: {
                travelTime: 29.12,
                travelTimeTraffic: 33.88,
                travelDistance: 15.54,
            },
            22: {
                travelTime: 18.03,
                travelTimeTraffic: 22.52,
                travelDistance: 8.98,
            },
            23: {
                travelTime: 15.43,
                travelTimeTraffic: 19.13,
                travelDistance: 8,
            },
            24: {
                travelTime: 13.27,
                travelTimeTraffic: 16.68,
                travelDistance: 4.31,
            },
            26: {
                travelTime: 27.65,
                travelTimeTraffic: 35.55,
                travelDistance: 14.7,
            },
            27: {
                travelTime: 26.18,
                travelTimeTraffic: 30.22,
                travelDistance: 13.68,
            },
            28: {
                travelTime: 12.47,
                travelTimeTraffic: 15.23,
                travelDistance: 6.82,
            },
            29: {
                travelTime: 16.8,
                travelTimeTraffic: 21.23,
                travelDistance: 8.35,
            },
            30: {
                travelTime: 17.17,
                travelTimeTraffic: 20.92,
                travelDistance: 9.34,
            },
        },
        25: {
            1: {
                travelTime: 38.07,
                travelTimeTraffic: 43.78,
                travelDistance: 28.4,
            },
            2: {
                travelTime: 41.18,
                travelTimeTraffic: 51.73,
                travelDistance: 26.9,
            },
            4: {
                travelTime: 23.87,
                travelTimeTraffic: 31.28,
                travelDistance: 11.56,
            },
            6: {
                travelTime: 19.53,
                travelTimeTraffic: 25.52,
                travelDistance: 8.71,
            },
            7: {
                travelTime: 26.93,
                travelTimeTraffic: 34.12,
                travelDistance: 10.81,
            },
            8: {
                travelTime: 21.8,
                travelTimeTraffic: 26.23,
                travelDistance: 10.05,
            },
            9: {
                travelTime: 27.82,
                travelTimeTraffic: 34.58,
                travelDistance: 14.91,
            },
            10: {
                travelTime: 17.98,
                travelTimeTraffic: 20.35,
                travelDistance: 7.01,
            },
            12: {
                travelTime: 29.23,
                travelTimeTraffic: 35.4,
                travelDistance: 12.52,
            },
            13: {
                travelTime: 25.5,
                travelTimeTraffic: 29.53,
                travelDistance: 13.99,
            },
            14: {
                travelTime: 13.07,
                travelTimeTraffic: 14.97,
                travelDistance: 5.36,
            },
            15: {
                travelTime: 23.55,
                travelTimeTraffic: 30.22,
                travelDistance: 12.17,
            },
            16: {
                travelTime: 27.3,
                travelTimeTraffic: 31.52,
                travelDistance: 15.29,
            },
            17: {
                travelTime: 16.5,
                travelTimeTraffic: 19.85,
                travelDistance: 7.62,
            },
            18: {
                travelTime: 7.67,
                travelTimeTraffic: 8.87,
                travelDistance: 3.55,
            },
            20: {
                travelTime: 14.82,
                travelTimeTraffic: 19.05,
                travelDistance: 5.61,
            },
            21: {
                travelTime: 20.17,
                travelTimeTraffic: 23.58,
                travelDistance: 8.22,
            },
            22: {
                travelTime: 30.17,
                travelTimeTraffic: 38.62,
                travelDistance: 17.03,
            },
            23: {
                travelTime: 29.42,
                travelTimeTraffic: 37.12,
                travelDistance: 16.44,
            },
            24: {
                travelTime: 29.5,
                travelTimeTraffic: 36.13,
                travelDistance: 15.16,
            },
            26: {
                travelTime: 10.37,
                travelTimeTraffic: 12.25,
                travelDistance: 4.23,
            },
            27: {
                travelTime: 23.15,
                travelTimeTraffic: 28.05,
                travelDistance: 8.87,
            },
            28: {
                travelTime: 28.72,
                travelTimeTraffic: 32.95,
                travelDistance: 19.73,
            },
            29: {
                travelTime: 19.97,
                travelTimeTraffic: 22.5,
                travelDistance: 7.77,
            },
            30: {
                travelTime: 17.67,
                travelTimeTraffic: 20.53,
                travelDistance: 7.87,
            },
        },
    },
};

export { fakeData1, fakeData2, fakeData1Unassigned, fakeData2Unassigned };
