module.exports = {
    jsonGeocodedData: [
        {
            name: "Allie",
            address: "4242 Branch Bend Ln, Charlotte, North Carolina, 28273",
            id: 1,
            latitude: 35.146123,
            longitude: -80.971573,
            method: null,
            type: "client",
        },
        {
            name: "Anastasia",
            address: "11807 Broadwater Ln, Charlotte, North Carolina 28273",
            id: 2,
            latitude: 35.1106926,
            longitude: -80.9697304,
            method: null,
            type: "client",
        },
        {
            name: "Anthony",
            address: "3707 Highview Rd, Charlotte, North Carolina, 28210",
            clients: [
                {
                    name: "James",
                    address:
                        "2135 Ferncliff Rd, Charlotte, North Carolina, 28211",
                    id: 7,
                    latitude: 35.16645949999999,
                    longitude: -80.814832,
                    method: null,
                    type: "client",
                },
                {
                    name: "Nava",
                    address:
                        "3737 Winding Creek Ln, Charlotte, North Carolina, 28226",
                    id: 12,
                    latitude: 35.142092,
                    longitude: -80.8181479,
                    method: null,
                    type: "client",
                },
            ],
            id: 3,
            latitude: 35.131711,
            longitude: -80.8278959,
            method: "driving",
            type: "employee",
        },
        {
            name: "Danny",
            address: "226 Queens Rd #69, Charlotte, North Carolina, 28204",
            id: 4,
            latitude: 35.209572,
            longitude: -80.82841189999999,
            method: null,
            type: "client",
        },
        {
            name: "Evan",
            address: "4020 Constable Ct, Charlotte, North Carolina, 28209",
            clients: [
                {
                    name: "Allie",
                    address:
                        "4242 Branch Bend Ln, Charlotte, North Carolina, 28273",
                    id: 1,
                    latitude: 35.146123,
                    longitude: -80.971573,
                    method: null,
                    type: "client",
                },
                {
                    name: "Anastasia",
                    address:
                        "11807 Broadwater Ln, Charlotte, North Carolina 28273",
                    id: 2,
                    latitude: 35.1106926,
                    longitude: -80.9697304,
                    method: null,
                    type: "client",
                },
                {
                    name: "Danny",
                    address:
                        "226 Queens Rd #69, Charlotte, North Carolina, 28204",
                    id: 4,
                    latitude: 35.209572,
                    longitude: -80.82841189999999,
                    method: null,
                    type: "client",
                },
                {
                    name: "Greg",
                    address: "3122 Eastway Dr, Charlotte, NC 28205",
                    id: 6,
                    latitude: 35.213196,
                    longitude: -80.783028,
                    method: null,
                    type: "client",
                },
                {
                    name: "Julia",
                    address: "2910 Parkway Ave, Charlotte, NC 28208",
                    id: 9,
                    latitude: 35.2424857,
                    longitude: -80.87749319999999,
                    method: null,
                    type: "client",
                },
                {
                    name: "Tamanna",
                    address: "426 N Tryon St, Charlotte, North Carolina, 28202",
                    id: 15,
                    latitude: 35.2298541,
                    longitude: -80.83860059999999,
                    method: null,
                    type: "client",
                },
            ],
            id: 5,
            latitude: 35.1809391,
            longitude: -80.8619298,
            method: "driving",
            type: "employee",
        },
        {
            name: "Greg",
            address: "3122 Eastway Dr, Charlotte, NC 28205",
            id: 6,
            latitude: 35.213196,
            longitude: -80.783028,
            method: null,
            type: "client",
        },
        {
            name: "James",
            address: "2135 Ferncliff Rd, Charlotte, North Carolina, 28211",
            id: 7,
            latitude: 35.16645949999999,
            longitude: -80.814832,
            method: null,
            type: "client",
        },
        {
            name: "Joe",
            address: "3201 Tallia Ct, Charlotte, North Carolina, 28269",
            id: 8,
            latitude: 35.31482370000001,
            longitude: -80.79285229999999,
            method: null,
            type: "client",
        },
        {
            name: "Julia",
            address: "2910 Parkway Ave, Charlotte, NC 28208",
            id: 9,
            latitude: 35.2424857,
            longitude: -80.87749319999999,
            method: null,
            type: "client",
        },
        {
            name: "Lisa",
            address: "3109 Connecticut Ave, Charlotte, North Carolina, 28205",
            id: 10,
            latitude: 35.232182,
            longitude: -80.7813516,
            method: null,
            type: "client",
        },
        {
            name: "Maria",
            address: "3506 Rindle Ct, Charlotte, North Carolina, 28269",
            clients: [
                {
                    name: "Joe",
                    address: "3201 Tallia Ct, Charlotte, North Carolina, 28269",
                    id: 8,
                    latitude: 35.31482370000001,
                    longitude: -80.79285229999999,
                    method: null,
                    type: "client",
                },
                {
                    name: "Lisa",
                    address:
                        "3109 Connecticut Ave, Charlotte, North Carolina, 28205",
                    id: 10,
                    latitude: 35.232182,
                    longitude: -80.7813516,
                    method: null,
                    type: "client",
                },
                {
                    name: "Rachana",
                    address: "2123 Beatties Ford Rd, Charlotte, NC 28216",
                    id: 13,
                    latitude: 35.2641691,
                    longitude: -80.85620080000001,
                    method: null,
                    type: "client",
                },
                {
                    name: "Spencer",
                    address:
                        "3800 Shamrock Dr, Charlotte, North Carolina, 28215",
                    id: 14,
                    latitude: 35.2344339,
                    longitude: -80.7605397,
                    method: null,
                    type: "client",
                },
            ],
            id: 11,
            latitude: 35.3156337,
            longitude: -80.8034535,
            method: "driving",
            type: "employee",
        },
        {
            name: "Nava",
            address: "3737 Winding Creek Ln, Charlotte, North Carolina, 28226",
            id: 12,
            latitude: 35.142092,
            longitude: -80.8181479,
            method: null,
            type: "client",
        },
        {
            name: "Rachana",
            address: "2123 Beatties Ford Rd, Charlotte, NC 28216",
            id: 13,
            latitude: 35.2641691,
            longitude: -80.85620080000001,
            method: null,
            type: "client",
        },
        {
            name: "Spencer",
            address: "3800 Shamrock Dr, Charlotte, North Carolina, 28215",
            id: 14,
            latitude: 35.2344339,
            longitude: -80.7605397,
            method: null,
            type: "client",
        },
        {
            name: "Tamanna",
            address: "426 N Tryon St, Charlotte, North Carolina, 28202",
            id: 15,
            latitude: 35.2298541,
            longitude: -80.83860059999999,
            method: null,
            type: "client",
        },
    ],
    transitMap: {
        3: {
            1: {
                travelTime: 23.68,
                travelTimeTraffic: 28.95,
                travelDistance: 12.86,
            },
            2: {
                travelTime: 27.07,
                travelTimeTraffic: 34.17,
                travelDistance: 13.46,
            },
            4: {
                travelTime: 19.17,
                travelTimeTraffic: 23.85,
                travelDistance: 6.65,
            },
            6: {
                travelTime: 20.33,
                travelTimeTraffic: 27.27,
                travelDistance: 7.46,
            },
            7: {
                travelTime: 10.37,
                travelTimeTraffic: 12.53,
                travelDistance: 3.46,
            },
            8: {
                travelTime: 33.3,
                travelTimeTraffic: 42.47,
                travelDistance: 19.03,
            },
            9: {
                travelTime: 25.57,
                travelTimeTraffic: 33.78,
                travelDistance: 11.75,
            },
            10: {
                travelTime: 26.38,
                travelTimeTraffic: 34.2,
                travelDistance: 9.59,
            },
            12: {
                travelTime: 5.2,
                travelTimeTraffic: 5.88,
                travelDistance: 1.36,
            },
            13: {
                travelTime: 27.32,
                travelTimeTraffic: 35.45,
                travelDistance: 13.82,
            },
            14: {
                travelTime: 25.65,
                travelTimeTraffic: 34.35,
                travelDistance: 10.02,
            },
            15: {
                travelTime: 23.9,
                travelTimeTraffic: 31.4,
                travelDistance: 12.67,
            },
        },
        5: {
            1: {
                travelTime: 19.9,
                travelTimeTraffic: 23.38,
                travelDistance: 11.31,
            },
            2: {
                travelTime: 22.05,
                travelTimeTraffic: 24.78,
                travelDistance: 12.36,
            },
            4: {
                travelTime: 15.17,
                travelTimeTraffic: 18.88,
                travelDistance: 6.98,
            },
            6: {
                travelTime: 19.33,
                travelTimeTraffic: 23.22,
                travelDistance: 10.59,
            },
            7: {
                travelTime: 11.33,
                travelTimeTraffic: 14.3,
                travelDistance: 3.62,
            },
            8: {
                travelTime: 23.17,
                travelTimeTraffic: 27.73,
                travelDistance: 13.37,
            },
            9: {
                travelTime: 15.43,
                travelTimeTraffic: 19.03,
                travelDistance: 6.1,
            },
            10: {
                travelTime: 23.05,
                travelTimeTraffic: 28.13,
                travelDistance: 10.75,
            },
            12: {
                travelTime: 14.53,
                travelTimeTraffic: 19.77,
                travelDistance: 4.63,
            },
            13: {
                travelTime: 17.2,
                travelTimeTraffic: 20.72,
                travelDistance: 8.17,
            },
            14: {
                travelTime: 24.65,
                travelTimeTraffic: 30.3,
                travelDistance: 13.16,
            },
            15: {
                travelTime: 13.78,
                travelTimeTraffic: 16.65,
                travelDistance: 7.02,
            },
        },
        11: {
            1: {
                travelTime: 28.37,
                travelTimeTraffic: 31.87,
                travelDistance: 21.7,
            },
            2: {
                travelTime: 33.42,
                travelTimeTraffic: 38.07,
                travelDistance: 23.2,
            },
            4: {
                travelTime: 21.63,
                travelTimeTraffic: 24.97,
                travelDistance: 13.1,
            },
            6: {
                travelTime: 23.83,
                travelTimeTraffic: 29.52,
                travelDistance: 8.63,
            },
            7: {
                travelTime: 29.15,
                travelTimeTraffic: 34.22,
                travelDistance: 16.62,
            },
            8: {
                travelTime: 3.28,
                travelTimeTraffic: 3.38,
                travelDistance: 0.77,
            },
            9: {
                travelTime: 18.3,
                travelTimeTraffic: 20.9,
                travelDistance: 10,
            },
            10: {
                travelTime: 20.7,
                travelTimeTraffic: 25.12,
                travelDistance: 7.44,
            },
            12: {
                travelTime: 32.62,
                travelTimeTraffic: 40.85,
                travelDistance: 19.29,
            },
            13: {
                travelTime: 15.8,
                travelTimeTraffic: 18.12,
                travelDistance: 7.29,
            },
            14: {
                travelTime: 20.62,
                travelTimeTraffic: 25.03,
                travelDistance: 7.63,
            },
            15: {
                travelTime: 17,
                travelTimeTraffic: 19.35,
                travelDistance: 9.61,
            },
        },
    },
};
